Loader and Select fixes
argo22com/arg-mobile-ui-kit pull request #4
Opened 2024-08-15 13:32 UTC by martinnovak22

2024-08-15 14:21 UTC, Kamony requested changes
@martinnovak22 zkusil sem se v tom trochu pošťourat a vypadá to, že ta špatná výška byla způsobená flex:1 v rootu. To sem smazal. Zkus nato prosím kouknout, zda je vše ok

2024-08-15 15:37 UTC, gynekolog commented on src/components/molecules/select/Select.tsx
Tohle není změna co by měla mít označení chore. Možná fix nebo feat, nemám celý kontext. Nejde o nic velkýho, jen dávám zpětnou vazbu když už jdu kolem.

2024-08-16 08:08 UTC, Kamony commented on src/components/molecules/select/Select.tsx
souhlas - @martinnovak22 pro příště bych podobný úpravy označil `fix:` nebo `feat:` podle toho co upravuješ. Viz https://www.conventionalcommits.org/en/v1.0.0/#specification

2024-08-16 11:47 UTC, Kamony approved these changes

2024-08-16 11:48 UTC, merged

2024-08-16 13:24 UTC, gynekolog commented on example/src/Root.tsx
@martinnovak22 Stejnej případ jako jsem už psal v https://github.com/argo22com/arg-mobile-ui-kit/pull/4#discussion_r1718582097
Přesnější název by byl, podle mě, `fix: Loader example`.
Čteš tyhle zprávy?

2024-08-16 13:41 UTC, martinnovak22 commented on example/src/Root.tsx
@gynekolog čtu je, jen tomu asi nerozumím na 100%, pokud doplním chybějící import, nepřijde mi, že bych něco fixoval 😁, ale pokusím se lépe porozumět

2024-08-16 14:39 UTC, Kamony commented
Z pohledu uživatele tyhle knihovny commitujes něco co mu opraví fungování.
Konkrétně mu nevyskočí červená hláška. Takže by to správně měl být fix

Dne pá 16. 8. 2024 15:41 uživatel Martin Novák ***@***.***>
napsal:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On example/src/Root.tsx
> <https://github.com/argo22com/arg-mobile-ui-kit/pull/4#discussion_r1719861251>
> :
>
> @gynekolog <https://github.com/gynekolog> čtu je, jen tomu asi nerozumím
> na 100%, pokud doplním chybějící import, nepřijde mi, že bych něco fixoval
> 😁, ale pokusím se lépe porozumět
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/argo22com/arg-mobile-ui-kit/pull/4#discussion_r1719861251>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFUFZYURFFCNEESUVOHOWSLZRX6QLAVCNFSM6AAAAABMSG5ZFSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBSG42DIOBRG4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2024-08-17 17:00 UTC, gynekolog commented on example/src/Root.tsx
@martinnovak22 Koukni třeba na hhttps://github.com/nestjs/nest/blob/master/CONTRIBUTING.md#type
Já si taky nejsem vždycky jistej. Ale v tomhle případě mi stačí kouknout na soubory co jsou v commitu a jsem si téměř jistej, že nejde o chore commit.